stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG_BRANCH: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build:
   image: docker:latest
   services:
     - docker:dind
   stage: build
   script:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
     - docker build -t $IMAGE_TAG_BRANCH .
     - docker push $IMAGE_TAG_BRANCH
   only:
     - master

deploy:
   image: registry.gitlab.com/ddd-sites/service-images/deploy:master
   stage: deploy
   variables:
     GIT_STRATEGY: none
   script:
     Empty
   only:
     - master
