stages:
  - compile
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG_BRANCH: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

compile:composer:
   image: composer:1.6
   stage: compile
   script:
      - cd src && composer install --no-dev -a --prefer-dist --ignore-platform-reqs --no-progress --no-suggest
      - cd .. && sh filter.sh
   only:
      - master
      - test
   cache:
      paths:
         - src/vendor
   artifacts:
      expire_in: 1 hour
      paths:
         - docker/app/
         - src/
         - Dockerfile

build:
   image: docker:latest
   services:
     - docker:dind
   stage: build
   script:
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
     - docker build --target production -t $IMAGE_TAG_BRANCH .
     - docker push $IMAGE_TAG_BRANCH
   only:
     - master

deploy:
   image: registry.gitlab.com/ddd-sites/service-images/deploy:master
   stage: deploy
   variables:
     GIT_STRATEGY: none
   script:
     Empty
   dependencies: []
   only:
     - master
     - test
