version: "3"
services:
  app:
    build:
      context: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/app
      - ./store/log:/var/www/html/log
    environment:
        DEBUG: 1
        DB_HOST: mysql
        DB_USER: root
        DB_PASS: pass
        DB_DATABASE: proteindesign
        DB_PORT: 3306
        MAIL_HOST: mail
        MAIL_PORT: 1025
        MAIL_USER:
        MAIL_PASS:
        MAIL_SECURE:
    depends_on:
      - composer
      - mail
      - mysql

  composer:
    image: composer:1.6
    working_dir: /var/app
    volumes:
      - ./src:/var/app
    command: install

  mysql:
    image: mysql:8.0.3
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_czech_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - ./store/mysql:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: proteindesign
      TZ: Europe/Prague

  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
